<?php

class ActionCode {

    //TRUCK_TYPE 
    const GET_ALL_TRUCK_TYPE = '99999';
    const GET_TRUCK_TYPE = '99998';
    const CREATE_TRUCK_TYPE = '99997';
    const UPDATE_TRUCK_TYPE = '99996';
    const DELETE_TRUCK_TYPE = '99995';
//TRUCK_REGISTRATION_HEAD_PART 
    const GET_ALL_TRUCK_REGISTRATION_HEAD_PART = '99994';
    const GET_TRUCK_REGISTRATION_HEAD_PART = '99993';
    const CREATE_TRUCK_REGISTRATION_HEAD_PART = '99992';
    const UPDATE_TRUCK_REGISTRATION_HEAD_PART = '99991';
    const DELETE_TRUCK_REGISTRATION_HEAD_PART = '99990';
//TRUCK_REGISTRATION_BACK_PART
    const GET_ALL_TRUCK_REGISTRATION_BACK_PART = '99989';
    const GET_TRUCK_REGISTRATION_BACK_PART = '99988';
    const CREATE_TRUCK_REGISTRATION_BACK_PART = '99987';
    const UPDATE_TRUCK_REGISTRATION_BACK_PART = '99986';
    const DELETE_TRUCK_REGISTRATION_BACK_PART = '99985';
//TRUCK_SHARING
    const GET_ALL_TRUCK_SHARING = '99984';
    const GET_TRUCK_SHARING = '99983';
    const CREATE_TRUCK_SHARING = '99982';
    const UPDATE_TRUCK_SHARING = '99981';
    const DELETE_TRUCK_SHARING = '99980';
//DRIVER 
    const GET_ALL_DRIVER = '99979';
    const GET_DRIVER = '99978';
    const CREATE_DRIVER = '99977';
    const UPDATE_DRIVER = '99976';
    const DELETE_DRIVER = '99975';
//DRIVER_TRUCK_REGULAR_USE
    const GET_ALL_DRIVER_TRUCK_REGULAR_USE = '99974';
    const GET_DRIVER_TRUCK_REGULAR_USE = '99973';
    const CREATE_DRIVER_TRUCK_REGULAR_USE = '99972';
    const UPDATE_DRIVER_TRUCK_REGULAR_USE = '99971';
    const DELETE_DRIVER_TRUCK_REGULAR_USE = '99970';
//DELIVERY_LOCATION
    const GET_ALL_DELIVERY_LOCATION = '99969';
    const GET_DELIVERY_LOCATION = '99968';
    const CREATE_DELIVERY_LOCATION = '99967';
    const UPDATE_DELIVERY_LOCATION = '99966';
    const DELETE_DELIVERY_LOCATION = '99965';
//WAY_ALLOWANCE_TRANSPORT_RATE 
    const GET_ALL_SET_WAY_ALLOWANCE_TRANSPORT_RATE = '99964';
    const GET_SET_WAY_ALLOWANCE_TRANSPORT_RATE = '99963';
    const CREATE_SET_WAY_ALLOWANCE_TRANSPORT_RATE = '99962';
    const UPDATE_SET_WAY_ALLOWANCE_TRANSPORT_RATE = '99961';
    const DELETE_SET_WAY_ALLOWANCE_TRANSPORT_RATE = '99960';
//TRANSPORTED_GOODS
    const GET_ALL_TRANSPORTED_GOODS = '99959';
    const GET_TRANSPORTED_GOODS = '99958';
    const CREATE_TRANSPORTED_GOODS = '99957';
    const UPDATE_TRANSPORTED_GOODS = '99956';
    const DELETE_TRANSPORTED_GOODS = '99955';
//CUSTOMER 
    const GET_ALL_CUSTOMER = '99954';
    const GET_CUSTOMER = '99953';
    const CREATE_CUSTOMER = '99952';
    const UPDATE_CUSTOMER = '99951';
    const DELETE_CUSTOMER = '99950';
//DIRECT_EXPENSE
    const GET_ALL_DIRECT_EXPENSE = '99949';
    const GET_DIRECT_EXPENSE = '99948';
    const CREATE_DIRECT_EXPENSE = '99947';
    const UPDATE_DIRECT_EXPENSE = '99946';
    const DELETE_DIRECT_EXPENSE = '99945';
//INDIRECT_EXPENSE
    const GET_ALL_INDIRECT_EXPENSE = '99944';
    const GET_INDIRECT_EXPENSE = '99943';
    const CREATE_INDIRECT_EXPENSE = '99942';
    const UPDATE_INDIRECT_EXPENSE = '99941';
    const DELETE_INDIRECT_EXPENSE = '99940';
//DEDUCT_MONEY_TRUCK_SHARING
    const GET_ALL_DEDUCT_MONEY_TRUCK_SHARING = '99939';
    const GET_DEDUCT_MONEY_TRUCK_SHARING = '99938';
    const CREATE_DEDUCT_MONEY_TRUCK_SHARING = '99937';
    const UPDATE_DEDUCT_MONEY_TRUCK_SHARING = '99936';
    const DELETE_DEDUCT_MONEY_TRUCK_SHARING = '99935';
//TIRE_HISTORY 
    const GET_ALL_TIRE_HISTORY = '99934';
    const GET_TIRE_HISTORY = '99933';
    const CREATE_TIRE_HISTORY = '99932';
    const UPDATE_TIRE_HISTORY = '99931';
    const DELETE_TIRE_HISTORY = '99930';
//TIRE_TRUCK
    const GET_ALL_TIRE_TRUCK = '99929';
    const GET_TIRE_TRUCK_BY_POSITION = '99928';
    const CREATE_TIRE_TRUCK = '99927';
    const UPDATE_TIRE_TRUCK = '99926';
    const DELETE_TIRE_TRUCK = '99925';
    const CHANGE_TIRE_TRUCK = '99591';
    
//DOCUMENT_NO
    const GET_ALL_DOCUMENT_NO = '99924';
    const GET_DOCUMENT_NO = '99923';
    const CREATE_DOCUMENT_NO = '99922';
    const UPDATE_DOCUMENT_NO = '99921';
    const DELETE_DOCUMENT_NO = '99920';
//STORE 
    const GET_ALL_STORE = '99919';
    const GET_STORE = '99918';
    const CREATE_STORE = '99917';
    const UPDATE_STORE = '99916';
    const DELETE_STORE = '99915';
//OWNER_TRUCK_SHARING
    const GET_ALL_OWNER_TRUCK_SHARING = '99914';
    const GET_OWNER_TRUCK_SHARING = '99913';
    const CREATE_OWNER_TRUCK_SHARING = '99912';
    const UPDATE_OWNER_TRUCK_SHARING = '99911';
    const DELETE_OWNER_TRUCK_SHARING = '99910';
//OTHER
    const GET_ALL_OTHER = '99909';
    const GET_OTHER = '99908';
    const CREATE_OTHER = '99907';
    const UPDATE_OTHER = '99906';
    const DELETE_OTHER = '99905';
//RELEASE_TRUCK_IN_BILL
    const GET_ALL_RELEASE_TRUCK_IN_BILL = '99904';
    const GET_RELEASE_TRUCK_IN_BILL = '99903';
    const CREATE_RELEASE_TRUCK_IN_BILL = '99902';
    const UPDATE_RELEASE_TRUCK_IN_BILL = '99901';
    const DELETE_RELEASE_TRUCK_IN_BILL = '99900';
//RELEASE_TRUCK_SHARING_BILL
    const GET_ALL_RELEASE_TRUCK_SHARING_BILL = '99899';
    const GET_RELEASE_TRUCK_SHARING_BILL = '99898';
    const CREATE_RELEASE_TRUCK_SHARING_BILL = '99897';
    const UPDATE_RELEASE_TRUCK_SHARING_BILL = '99896';
    const DELETE_RELEASE_TRUCK_SHARING_BILL = '99895';
//TRUCK_IN_WORKING_BILL
    const GET_ALL_TRUCK_IN_WORKING_BILL = '99888';
    const GET_TRUCK_IN_WORKING_BILL = '99887';
    const CREATE_TRUCK_IN_WORKING_BILL = '99886';
    const UPDATE_TRUCK_IN_WORKING_BILL = '99885';
    const DELETE_TRUCK_IN_WORKING_BILL = '99884';
//TRUCK_SHARING_WORKING_BILL
    const GET_ALL_TRUCK_SHARING_WORKING_BILL = '99883';
    const GET_TRUCK_SHARING_WORKING_BILL = '99882';
    const CREATE_TRUCK_SHARING_WORKING_BILL = '99881';
    const UPDATE_TRUCK_SHARING_WORKING_BILL = '99880';
    const DELETE_TRUCK_SHARING_WORKING_BILL = '99879';
//MILE_NUMBER_CHANGE_ENGINE_OIL
    const GET_ALL_MILE_NUMBER_CHANGE_ENGINE_OIL = '99878';
    const GET_MILE_NUMBER_CHANGE_ENGINE_OIL = '99877';
    const CREATE_MILE_NUMBER_CHANGE_ENGINE_OIL = '99876';
    const UPDATE_MILE_NUMBER_CHANGE_ENGINE_OIL = '99875';
    const DELETE_MILE_NUMBER_CHANGE_ENGINE_OIL = '99874';
//TRUCK_BRAND 
    const GET_ALL_TRUCK_BRAND = '99873';
    const GET_TRUCK_BRAND = '99872';
    const CREATE_TRUCK_BRAND = '99871';
    const UPDATE_TRUCK_BRAND = '99870';
    const DELETE_TRUCK_BRAND = '99869';
//LOGIN--LOGOUT
    const LOGIN = '99868';
    const LOGOUT = '99867';
//CHANGE_ENGINE_OIL
    const GET_ALL_CHANGE_ENGINE_OIL = '99865';
    const GET_CHANGE_ENGINE_OIL = '99864';
    const CREATE_CHANGE_ENGINE_OIL = '99863';
    const UPDATE_CHANGE_ENGINE_OIL = '99862';
    const DELETE_CHANGE_ENGINE_OIL = '99861';
    const GET_ALL_REPORT_TRUCK_IN_SHIPPING_PRODUCT_DAILY_OIL = '99860';
//REFUEL
    const GET_ALL_REFUEL = '99859';
    const GET_REFUEL = '99858';
    const CREATE_REFUEL = '99857';
    const UPDATE_REFUEL = '99866';
    const DELETE_REFUEL = '99865';
//DRIVERS_WAGE
    const GET_ALL_DRIVERS_WAGE = '99864';
    const GET_DRIVERS_WAGE = '99863';
    const CREATE_DRIVERS_WAGE = '99862';
    const UPDATE_DRIVERS_WAGE = '99861';
    const DELETE_DRIVERS_WAGE = '99860';
//TRUCK_SHARING_WAGE
    const GET_ALL_TRUCK_SHARING_WAGE = '99859';
    const GET_TRUCK_SHARING_WAGE = '99858';
    const CREATE_TRUCK_SHARING_WAGE = '99857';
    const UPDATE_TRUCK_SHARING_WAGE = '99856';
    const DELETE_TRUCK_SHARING_WAGE = '99855';
//ADDITIONAL_INCOME_AND_DEDUCT_MONEY_MONTHLY_OF_DRIVER
    const GET_ALL_ADDITIONAL_INCOME_AND_DEDUCT_MONEY_MONTHLY_OF_DRIVER = '99854';
    const GET_ADDITIONAL_INCOME_AND_DEDUCT_MONEY_MONTHLY_OF_DRIVER = '99853';
    const CREATE_ADDITIONAL_INCOME_AND_DEDUCT_MONEY_MONTHLY_OF_DRIVER = '99852';
    const UPDATE_ADDITIONAL_INCOME_AND_DEDUCT_MONEY_MONTHLY_OF_DRIVER = '99851';
    const DELETE_ADDITIONAL_INCOME_AND_DEDUCT_MONEY_MONTHLY_OF_DRIVER = '99850';
    const GET_RELEASE_TRUCK_IN_BILL_BY_BILL_RELEASE_TRUCK_IN_NO = '99849';
//GAS_STATION 
    const GET_ALL_GAS_STATION = '99848';
    const GET_GAS_STATION = '99847';
    const CREATE_GAS_STATION = '99846';
    const UPDATE_GAS_STATION = '99845';
    const DELETE_GAS_STATION = '99844';
//MONTHLY_ADDITIONAL_COST
    const GET_ALL_MONTHLY_ADDITIONAL_COST = '99843';
    const GET_MONTHLY_ADDITIONAL_COST = '99842';
    const CREATE_MONTHLY_ADDITIONAL_COST = '99841';
    const UPDATE_MONTHLY_ADDITIONAL_COST = '99840';
    const DELETE_MONTHLY_ADDITIONAL_COST = '99839';
    const GET_ALL_REPORT_INCOME_OUTCOME_PER_TRIP_PER_DAY = '99838';
//CENTRAL_MONEY 
    const GET_ALL_CENTRAL_MONEY = '99837';
    const GET_CENTRAL_MONEY = '99836';
    const CREATE_CENTRAL_MONEY = '99834';
    const UPDATE_CENTRAL_MONEY = '99833';
    const DELETE_CENTRAL_MONEY = '99832';
//REPORT_TIRE_EACH_TYPE 
    const GET_ALL_REPORT_TIRE_EACH_TYPE = '99831';
    const GET_ALL_REPORT_DRIVER_LICENSE_EXPIRED = '99830';
    const GET_ALL_REPORT_TRUCK_MUST_RENEWAL_REGISTRATION = '99829';
    const GET_ALL_REPORT_TRUCK_ANNUAL_INSURANCE_RENEWAL_DATE = '99828';
    const GET_ALL_REPORT_TRUCK_RENEW_PRODUCTS_INSURANCE = '99827';
    const GET_ALL_REPORT_TRUCK_TIRE_WILL_BE_EXPIRING = '99826';
    const GET_ALL_REPORT_TRUCK_IN_SHIPPING_PRODUCTS_BY_CUSTOMER = '99825';
    const GET_ALL_REPORT_MONTHLY_TRUCK_WORKING = '99824';
    const GET_ALL_REPORT_MONTHLY_TRUCK_SHARING_WORKING = '99823';
    const GET_ALL_REPORT_SHIPPING_PRODUCTS_BY_CUSTOMER_AND_PRODUCT = '99822';
    const GET_ALL_REPORT_SHIPPING_PRODUCTS_BY_CUSTOMER_AND_WAY = '99821';

    /* truck repair  */
    const GET_ALL_REPAIR_TYPE = '99700';
    const GET_REPAIR_TYPE = '99699';
    const CREATE_REPAIR_TYPE = '99698';
    const UPDATE_REPAIR_TYPE = '99697';
    const DELETE_REPAIR_TYPE = '99696';
//REPAIR_FACILITY
    const GET_ALL_REPAIR_FACILITY = '99695';
    const GET_REPAIR_FACILITY = '99694';
    const CREATE_REPAIR_FACILITY = '99693';
    const UPDATE_REPAIR_FACILITY = '99692';
    const DELETE_REPAIR_FACILITY = '99691';
//REPAIR_IN_BILL
    const GET_ALL_REPAIR_IN_BILL = '99690';
    const GET_REPAIR_IN_BILL = '99689';
    const CREATE_REPAIR_IN_BILL = '99688';
    const UPDATE_REPAIR_IN_BILL = '99687';
    const DELETE_REPAIR_IN_BILL = '99686';
    const GET_REPAIR_IN_BILL_BY_LICENSE_PLATE = '99685';
//REPAIR_IN 
    const GET_ALL_REPAIR_IN = '99684';
    const GET_REPAIR_IN = '99683';
    const CREATE_REPAIR_IN = '99682';
    const UPDATE_REPAIR_IN = '99681';
    const DELETE_REPAIR_IN = '99680';
    const GET_REPAIR_IN_BY_REPAIR_BILL_CODE = '99679';
    const GET_REPAIR_IN_REPORT_DAILY_REPAIR = '99678';
    const CREATE_REPAIR_IN_TEST = "99677";
    const PRINT_REPAIR_FACILITY = "99676";
//REPAIR_OUT 
    const GET_ALL_REPAIR_OUT = '99675';
    const GET_REPAIR_OUT = '99674';
    const CREATE_REPAIR_OUT = '99673';
    const UPDATE_REPAIR_OUT = '99672';
    const DELETE_REPAIR_OUT = '99671';
    const REPORT_REPAIR_OUT = '99670';
//
    const REPORT_DAILY_TRUCK_REPAIR_OUT = '99669';
//
    const DELETE_REPAIR_IN_TRUCK_PARTS = '99668';
//
    const REPORT_DAILY_TRUCK_REPAIR_IN = '99667';
//PROVINCE 
    const GET_ALL_PROVINCE = '99666';
    const GET_PROVINCE = '99665';
    const CREATE_PROVINCE = '99664';
    const UPDATE_PROVINCE = '99663';
    const DELETE_PROVINCE = '99662';

    /* truck inventory system */
//TIS_PRODUCT
    const GET_ALL_TIS_PRODUCT = '99661';
    const GET_TIS_PRODUCT = '99660';
    const CREATE_TIS_PRODUCT = '99659';
    const UPDATE_TIS_PRODUCT = '99658';
    const DELETE_TIS_PRODUCT = '99657';
//TIS_PRODUCT_TYPE
    const GET_ALL_TIS_PRODUCT_TYPE = '99656';
    const GET_TIS_PRODUCT_TYPE = '99654';
    const CREATE_TIS_PRODUCT_TYPE = '99653';
    const UPDATE_TIS_PRODUCT_TYPE = '99652';
    const DELETE_TIS_PRODUCT_TYPE = '99651';
//TIS_RECEIVE_PRODUCT 
    const GET_ALL_TIS_RECEIVE_PRODUCT = '99650';
    const GET_TIS_RECEIVE_PRODUCT = '99649';
    const CREATE_TIS_RECEIVE_PRODUCT = '99648';
    const UPDATE_TIS_RECEIVE_PRODUCT = '99647';
    const DELETE_TIS_RECEIVE_PRODUCT = '99646';
//TIS_PRODUCT_TURNOVER
    const GET_ALL_TIS_PRODUCT_TURNOVER = '99645';
    const GET_TIS_PRODUCT_TURNOVER = '99644';
    const CREATE_TIS_PRODUCT_TURNOVER = '99643';
    const UPDATE_TIS_PRODUCT_TURNOVER = '99642';
    const DELETE_TIS_PRODUCT_TURNOVER = '99641';
//TIS_UNIT
    const GET_ALL_TIS_UNIT = '99640';
    const GET_TIS_UNIT = '99639';
    const CREATE_TIS_UNIT = '99638';
    const UPDATE_TIS_UNIT = '99637';
    const DELETE_TIS_UNIT = '99636';
//TIS_RECEIVE_PRODUCT_DETAIL
    const GET_ALL_TIS_RECEIVE_PRODUCT_DETAIL = '99635';
    const GET_TIS_RECEIVE_PRODUCT_DETAIL = '99634';
    const CREATE_TIS_RECEIVE_PRODUCT_DETAIL = '99633';
    const UPDATE_TIS_RECEIVE_PRODUCT_DETAIL = '99632';
    const DELETE_TIS_RECEIVE_PRODUCT_DETAIL = '99631';
//TIS_REQUISITION_PRODUCT 
    const GET_ALL_TIS_REQUISITION_PRODUCT = '99630';
    const GET_TIS_REQUISITION_PRODUCT = '99629';
    const CREATE_TIS_REQUISITION_PRODUCT = '99628';
    const UPDATE_TIS_REQUISITION_PRODUCT = '99627';
    const DELETE_TIS_REQUISITION_PRODUCT = '99626';
//
    const GET_RELEASE_TRUCK_SHARING_BILL_BY_RELEASE_TRUCK_SHARING_BILL_NO = '99625';
//COLOR 
    const GET_ALL_COLOR = '99624';
    const GET_COLOR_BY_NAME = '99623';
    const CREATE_COLOR = '99622';
    const UPDATE_COLOR = '99621';
    const DELETE_COLOR = '99620';
//BATTERY
    const GET_ALL_BATTERY = '99619';
    const GET_BATTERY_BY_NAME = '99618';
    const CREATE_BATTERY = '99617';
    const UPDATE_BATTERY = '99616';
    const DELETE_BATTERY = '99615';
//COUNTRY 
    const GET_ALL_COUNTRY = '99614';
    const GET_COUNTRY = '99613';
    const CREATE_COUNTRY = '99613';
    const UPDATE_COUNTRY = '99612';
    const DELETE_COUNTRY = '99611';
    const GET_PROVINCE_BY_COUNTRY = '99610';
    //Tire type
    const GET_TIRE_TYPE = "99609";
    const INSERT_TIRE_TYPE = "99608";
    const UPDATE_TIRE_TYPE = "99607";
    const DELETE_TIRE_TYPE = "99606";
    //Staff
    const GET_STAFF = "99605";
    const GET_ALL_STAFF = "99604";
    const INSERT_STAFF = "99603";
    const UPDATE_STAFF = "99602";
    const DELETE_STAFF = "99601";
    const STAFF_RESET_PASS = "99600";
    //Department
    const GET_ALL_DEPARTMENT = "99599";
    const GET_DEPARTMENT_BY_ID = "99598";
    const INSERT_DEPARTMENT = "99597";
    const UPDATE_DEPARTMENT = "99596";
    //Branch
    const GET_ALL_BRANCH = "99595";
    const GET_BRANCH_BY_ID = "99594";
    const INSERT_BRANCH = "99593";
    const UPDATE_BRANCH = "99592";

}
